name: yummycakes
description: "Store App"


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.0
  map: ^2.0.2
  geolocator: ^11.0.0
  geocoding: ^2.2.0
  http: ^1.2.1
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:


  uses-material-design: true
  assets:
     - asset/img/logo/logo.jpeg
     - asset/img/profile/pp.png

